services:
  qiaoqiaoyun-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/jeecgdocker/qiaoqiaoyun-mysql:2.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: qiaoqiaoyun-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
    networks:
      - qiaoqiaoyun

  qiaoqiaoyun-redis:
    image: registry.cn-hangzhou.aliyuncs.com/jeecgdocker/redis:5.0
    ports:
      - 6379:6379
    restart: always
    hostname: qiaoqiaoyun-redis
    container_name: qiaoqiaoyun-redis
    networks:
      - qiaoqiaoyun

  qiaoqiaoyun-mongo:
    image: registry.cn-hangzhou.aliyuncs.com/jeecgdocker/qiaoqiaoyun-mongo:2.0.1
    restart: always
    container_name: qiaoqiaoyun-mongo
    ports:
      - 27017:27017
    networks:
      - qiaoqiaoyun

  qiaoqiaoyun-system:
    image: registry.cn-hangzhou.aliyuncs.com/jeecgdocker/qiaoqiaoyun-system:2.0.1
    restart: on-failure
    depends_on:
      - qiaoqiaoyun-mysql
      - qiaoqiaoyun-redis
    container_name: qiaoqiaoyun-system
    hostname: qiaoqiaoyun-system
    ports:
      - 8080:8080
    networks:
      - qiaoqiaoyun

  qiaoqiaoyun-nginx:
    image: registry.cn-hangzhou.aliyuncs.com/jeecgdocker/qiaoqiaoyun-nginx:2.0.1
    container_name: qiaoqiaoyun-nginx
    depends_on:
      - qiaoqiaoyun-system
    networks:
      - qiaoqiaoyun
    ports:
      - 80:80

networks:
  qiaoqiaoyun:
    name: qiaoqiaoyun
