FROM registry.cn-hangzhou.aliyuncs.com/jeecgdocker/alpine-java:8_server-jre_unlimited

MAINTAINER jeecgos@163.com

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

WORKDIR /qiaoqiaoyun

EXPOSE 80

ADD ./docker/config/application-prod.yml ./config/application-prod.yml
ADD qiaoqiaoyun-start-2.2.1.jar ./

CMD sleep 60;java -Djava.security.egd=file:/dev/./urandom -javaagent:qiaoqiaoyun-start-2.2.1.jar="-pwd 5eez3Vqil97n" -jar -Dfile.encoding=UTF-8 qiaoqiaoyun-start-2.2.1.jar